name: Sugerir uma melhoria
description: Proponha uma melhoria para o app.
body:
  - type: textarea
    id: problem
    attributes:
      label: Qual problema você quer resolver?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Como a melhoria poderia funcionar?
    validations:
      required: true
